server:
  port: 9090

spring:
  application:
    name: dev-util
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/develop-util?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1  # 主机地址
    port: 6379
    cache:
      redis:
        time-to-live: -1 #毫秒
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: a4b2eb9e-3b54-496a-b7e4-407ad36fb374
        username: nacos
        password: nacos
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # 发送邮件配置
  # 发送邮件相关配置
  mail:
    host: smtp.qq.com # 此处使用的是qq邮箱进行邮件发送
    username: shijie97@qq.com # 发送邮件的账号（也就是本人账号）
    password: hdduyrllmsiibfhj # 账号秘钥（注意这不是登录你QQ邮箱的密码！该秘钥在开启SMTP服务时会给出。）
    default-encoding: UTF-8 #编码风格
    properties:
      mail: 776289764@qq.com
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  configuration:
    #默认不显示SQL日志
    #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn:
      panyucbale:
        springboot:
          mapper: debug

http:
  maxTotal: 100         #最大连接数
  defaultMaxPerRoute: 20  #并发数
  connectTimeout: 1000   #创建连接的最长时间
  connectionRequestTimeout: 500  #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true  #提交请求前测试连接是否可用
  validateAfterInactivity: 3000000   #可用空闲连接过期时间,重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放socket重新建立

